import React,{useMemo,useState} from 'react';
import {ResponsiveContainer,AreaChart,Area,BarChart,Bar,ScatterChart,Scatter,CartesianGrid,XAxis,YAxis,Tooltip,ReferenceLine} from 'recharts';
import {flowMetrics,forecast} from './flow.js';
const value=n=>n===null?'Sin datos':n.toFixed(1);
function Chart({children}){return <div className="chart"><ResponsiveContainer>{children}</ResponsiveContainer></div>}
export default function FlowPanel({items,now}){
 const [days,setDays]=useState(90),[remaining,setRemaining]=useState(30);
 const metrics=useMemo(()=>flowMetrics(items,now,days),[items,now,days]);
 const prediction=useMemo(()=>{let seed=123456789;return forecast(metrics.daily,remaining,now,1000,()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296;});},[metrics,remaining,now]);
 return <section id="flow"><div className="panel-head"><div><h2>Flujo de trabajo · FlowViz</h2><p>Historial de Azure DevOps · días naturales UTC</p></div><select aria-label="Periodo de flujo" value={days} onChange={e=>setDays(Number(e.target.value))}>{[30,90,180].map(n=><option key={n} value={n}>{n} días</option>)}</select></div>
 <div className="notice">Cobertura histórica: {metrics.coverage}/{metrics.total} tickets. Ciclo: primera entrada en progreso hasta el cierre actual. Removed se excluye de entregas. Los estados desconocidos se excluyen de las series. La eficiencia estima tiempo activo sin bloqueo ni columna terminada; para reproducir Power BI exactamente se necesita el mismo mapeo de columnas y filtros.</div>
 <div className="metrics">{[['Ciclo P50',metrics.p50===null?'Sin datos':value(metrics.p50)+' d'],['Ciclo P85',metrics.p85===null?'Sin datos':value(metrics.p85)+' d'],['WIP diario medio',metrics.coverage?value(metrics.averageWip):'Sin datos'],['Flujo neto',metrics.coverage?metrics.net:'Sin datos']].map(([label,v])=><div className="metric purple" key={label}><div className="metric-label">{label}</div><strong>{v}</strong></div>)}</div>
 {metrics.coverage>0&&<><div className="chart-grid"><section className="panel"><h2>Flujo acumulado</h2><Chart><AreaChart data={metrics.daily}><CartesianGrid stroke="#2b3039"/><XAxis dataKey="date" minTickGap={45}/><YAxis allowDecimals={false}/><Tooltip/>{[['Completado','#55d5b3'],['WIP','#b399ff'],['Pendiente','#f5b766']].map(([key,color])=><Area key={key} dataKey={key} stackId="flow" stroke={color} fill={color} fillOpacity={.3}/>)}</AreaChart></Chart></section>
 <section className="panel"><h2>Entregas por día</h2><Chart><BarChart data={metrics.daily}><XAxis dataKey="date" minTickGap={45}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="Entregados" fill="#55d5b3"/></BarChart></Chart></section>
 <section className="panel"><h2>Dispersión del tiempo de ciclo</h2><p>{metrics.cycles.length} cierres con inicio conocido · P95: {value(metrics.p95)} d</p><Chart><ScatterChart><XAxis dataKey="date" type="category" name="Cierre" allowDuplicatedCategory={false}/><YAxis dataKey="days" name="Días"/><Tooltip cursor={{strokeDasharray:'3 3'}}/>{metrics.p85!==null&&<ReferenceLine y={metrics.p85} label="P85" stroke="#f5b766"/>}<Scatter data={metrics.cycles} fill="#b399ff"/></ScatterChart></Chart></section>
 <section className="panel"><h2>Antigüedad del trabajo en progreso</h2><Chart><BarChart data={metrics.aging}><XAxis dataKey="id"/><YAxis/><Tooltip/><Bar dataKey="days" name="Días en progreso" fill="#f384a0"/>{metrics.p85!==null&&<ReferenceLine y={metrics.p85} label="P85" stroke="#f5b766"/>}</BarChart></Chart><p>{metrics.aging.filter(i=>i.risk).length} tickets superan el P85 histórico.</p></section>
 <section className="panel"><h2>Tiempo por columna / estado</h2><Chart><BarChart data={metrics.columns}><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="days" name="Días acumulados" fill="#b399ff"/></BarChart></Chart><p>Eficiencia estimada: {metrics.efficiency===null?'Sin datos':(metrics.efficiency*100).toFixed(1)+'%'} · {value(metrics.blockedDays)} días bloqueados · {metrics.blockedNow} bloqueados en progreso.</p></section></div></>}
 <section className="panel"><h2>Pronóstico Monte Carlo</h2><label>Tickets restantes <input aria-label="Tickets restantes" type="number" min="1" max="100000" value={remaining} onChange={e=>setRemaining(Number(e.target.value))}/></label><p>Muestreo de semanas UTC completas, incluyendo semanas sin entregas; 1,000 simulaciones.</p>{prediction?<><div className="health-stats">{prediction.percentiles.map(r=><span key={r.p}><b>{Math.round(r.p*100)}%: {r.date||'Fuera del horizonte'}</b>{r.weeks===null?'Más de 520 semanas':r.weeks+' semanas'}</span>)}</div><p>{prediction.weeks} semanas de historial. Estimación probabilística, sujeta a que se mantenga el ritmo.</p></>:<p>{!Number.isInteger(remaining)||remaining<1||remaining>100000?'Introduce entre 1 y 100,000 tickets enteros.':'Se requieren al menos dos semanas completas y alguna entrega con historial. No se genera una fecha cuando falta evidencia.'}</p>}</section></section>;
}
